default_agent: mcp_server_agentcore
agents:
  mcp_server_agentcore:
    name: mcp_server_agentcore
    entrypoint: /Users/ksdyb/Documents/src/mcp-tools/mcp_server/mcp_server.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::262976740991:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-7f3ae149b4
      execution_role_auto_create: false
      account: '262976740991'
      region: us-west-2
      ecr_repository: 262976740991.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-mcp_server_agentcore
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: MCP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: mcp_server_agentcore-eBb7qA4fpg
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:262976740991:runtime/mcp_server_agentcore-eBb7qA4fpg
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-mcp_server_agentcore-builder
      execution_role: arn:aws:iam::262976740991:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-7f3ae149b4
      source_bucket: bedrock-agentcore-codebuild-sources-262976740991-us-west-2
    authorizer_configuration:
      customJWTAuthorizer:
        allowedClients:
        - 6rpjijend9osng4io4qiuv31ad
        discoveryUrl: https://cognito-idp.us-west-2.amazonaws.com/us-west-2_XZPaAsJW8/.well-known/openid-configuration
    oauth_configuration: null
